services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - FRONTEND_URL=http://localhost:8085
      - GEMINI_API_KEY=YOUR_GEMINI_KEY
      - OPENAI_API_KEY=YOUR_OPENAI_KEY

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
